version: '3.7'
services:
  postgres-prod:
    image: postgres:9.6
    container_name: docker-prod
    environment:
      - POSTGRES_DB=dockerprod
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks: 
      - webnet
    ports:
      - "4242:5432"
  app:
    build: .
    command: npm start
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres-prod
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - postgres-prod
    networks: 
      - webnet
networks: 
  webnet: