version: '3.7'
services:
  postgres-dev:
    image: postgres:11.2-alpine
    container_name: docker-dev
    environment:
      - POSTGRES_DB=dockerdev
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks: 
      - webnet
    volumes:
      - ./server_db:/var/lib/postgresql/data
    ports:
      - "4201:5432"
  postgres-test:
    image: postgres:11.2-alpine
    container_name: docker-test
    environment:
      - POSTGRES_DB=dockertest
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks: 
      - webnet
    ports:
      - "4202:5432"
  app:
    build:
      context: .
      target: development
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:${PORT}"
      - "9229:9229"
    depends_on:
      - postgres-dev
      - postgres-test
    environment:
      - DB_HOST=postgres-dev
      - DB_HOST_II=postgres-test
      - NODE_ENV=${NODE_ENV}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
    networks: 
      - webnet
networks: 
  webnet:
volumes:
  server_db: